select * from C,S,G,D,GS,DS;
select * from C;
select * from S;
select * from G;
select * from D;
select * from GS;
select * from DS;
select cno,phone,adder,gno from C where cname='张三';
select kind,price,inventory from S where sname='horse';
select sname,gnum from C,G,GS,S where C.cno=G.cno and G.gno=GS.gno and S.sno=GS.sno and cname='张三';
select sname,inventory from S;
select sname from C,S,G,GS where C.cno=G.cno and G.gno=GS.gno and S.sno=GS.sno and cname='张三' order by price DESC;
select sname from C,S,G,GS where C.cno=G.cno and G.gno=GS.gno and S.sno=GS.sno and cname='张三' order by price ASC;
select sname,inventory from C,G,S,GS where C.cno=G.cno and G.gno=GS.gno and S.sno=GS.sno and cname='张三' ;
select sum(dmoney) from C,D where C.cno=D.cno and cname='张三';
select dno,pay_yn from C,D where C.cno=D.cno and cname='张三';
select dno,s_yn,m_yn from C,D where C.cno=D.cno and cname ='张三' ;
select sname,sum(snum) from C,S,D,DS where C.cno=D.cno and D.dno=DS.dno and DS.sno=S.sno and cname='张三' group by sname;
select sum(gnum*price) from C,S,G,GS where C.cno=G.cno and G.gno=GS.gno and GS.sno=S.sno and cname='张三';
select distinct C.cno,cname from C,D where C.cno=D.cno and pay_yn='Y';
select distinct C.cno,cname from C,D where C.cno=D.cno and s_yn='N';
select * from D where dno='D001';
select dno from C,D where C.cno=D.cno and C.cno='张三';
select C.cno,cname from C,G where C.cno=G.cno and G.gno='G001';
select C.cno,cname from C,D where C.cno=D.cno and dno='D001';
select cname,phone,adder from C where cno='C001';