USE Shop;
ALTER TABLE GS
    ALTER COLUMN GNo CHAR(10) NOT NULL;
ALTER TABLE GS ADD CONSTRAINT pk_GS_GNo PRIMARY KEY (GNo);
ALTER TABLE GS ADD CONSTRAINT fk_GS_SNo FOREIGN KEY (SNo) REFERENCES S(SNo);